name = "theophysics-worker"
main = "src/index.js"
compatibility_date = "2025-10-01"

# Bind your R2 bucket
[[r2_buckets]]
binding = "VAULT"
bucket_name = "theophysics-vault"

# KV for note index & AI keys
[[kv_namespaces]]
binding = "NOTE_INDEX"
id = "REPLACE_WITH_KV_ID"

# Durable Object for per-note discussion
[durable_objects]
bindings = [{ name = "NoteRoom", class_name = "NoteRoom" }]

[vars]
HMAC_ALGO = "SHA-256"

[triggers]
crons = ["*/15 * * * *"]
